---
title: A micro-longitudinal investigation of verbal and nonverbal sexual consent cue use among university students
author:
  - name: Stephanie B. Ward 
    orcid: https://orcid.org/0000-0002-8191-0158
    corresponding: true
    email: sbward@wisc.edu
    affiliations:
      - Department of Psychology, University of Wisconsin-Madison
keywords:
  - Sexual consent
  - Sexual assault
  - College student
  - Alcohol
date: last-modified
bibliography: zotero_lib.bib
csl: american-medical-association.csl
number-sections: false 
editor_options: 
  chunk_output_type: console
editor:
  wrap: 12
---

## SPECIFIC AIMS

Sexual consent is a complex process involving thoughts, feelings, and
behaviors used to determine and express willingness to engage in sexual
activity with a particular person in a particular context; the presence
of consent distinguishes wanted sexual encounters from sexual assault
[@muehlenhardComplexitiesSexualConsent2016] 1 People can communicate
consent using active consent cues, which may be verbal or nonverbal and
direct or indirect, ranging from a clear and spoken “yes” to subtle body
language.[@willisAssessingWithinPersonVariability2021]2 Programs
designed to prevent sexual assault often target consent communication,
but a substantial gap exists between their curriculum and the varied
consent practices that young people use during sexual encounters.3
Individual factors such as demographics, attitudes,4 and typical
behavior5 are linked to differences in consent cue use. Gender, for
instance, is a significant factor,6 but there is mixed evidence
regarding its associations with consent cues. Some research suggests men
are more likely than women to use verbal cues relative to indirect,
nonverbal cues,7 while other studies observe interactions or trends that
imply gender differences hinge on context.8,9 Unpacking the complexity
around person-level and situational factors could illuminate more
information about the conditions under which particular individuals are
likely to use certain types of consent cues.

Research on the contexts in which individuals use certain consent cues
has been limited. This is a problem because situational factors such as
sexual behavior type, co-occurring intoxication, and feelings of arousal
and pleasure are linked to within-person differences in consent cue
use.10,11 Within-person variability has been shown to account for more
than 70% of the variance in sexual consent cues,12 indicating that
context may be more informative than individual differences in how
people communicate consent in general. Researchers examining situational
factors related to consent have done so by conducting systematic,
within-person comparisons of two matched events,8 or by grounding
responses to each person’s most recent sexual encounter, which could
have occurred weeks to months in the past.13 By asking people to
remember past events, these studies risk greater recall bias relative to
micro-longitudinal studies, which assess situational factors closer in
time to when consent communication occurs.

Although diaries and ecological momentary assessment have been used
extensively in other behavioral science research to illuminate important
time-varying situational predictors of health-risk behaviors,14–16 only
one published investigation of this kind has been conducted in the
sexual consent research space. Willis and colleagues surveyed
participants three times per day for 28 days and found that those
engaging in more intimate sexual behavior  (i.e., vaginal or anal
penetration) reported more active consent communication than those
engaging in less intimate behaviors, while no significant event-level
associations between alcohol use and verbal or nonverbal consent cue use
were observed.10,12 However, this research examined a limited set of
predictors and reflected a specific subpopulation of adults in committed
relationships; the current project builds on their findings by probing
person- and event-level associations with consent cue use among college
students while expanding the range of possible predictors. Examining
these associations in different samples and in relation to a wider array
of variables is a crucial next step toward isolating more actionable
targets for consent communication interventions. 

To advance the field, this project leverages micro-longitudinal data to
identify proximal situational correlates of verbal and nonverbal consent
cues that explain variance above and beyond the effects of significant
individual factors. I will analyze 501 sexual events reported by 152
college students to extend previous research investigating between- and
within-person variation in consent communication, with the goal of
informing future research and sexual assault prevention efforts focused
on changing consent behavior. Specifically, I propose the following
aims. 

### Aim 1: Characterize between-person differences in consent cue usage.

We will examine attitudinal and behavioral of consent cue usage and
whether use varies by gender. **Hypotheses:** *(H1a):* More permissive
individual and perceived peer attitudes toward alcohol-involved consent
and sexual coercion/rape will be negatively related to verbal and
nonverbal cue use, particularly among men vs. women. *(H1b):* Sexual
risk behavior, hazardous alcohol use, and typical nonverbal approach to
consent will be negatively related to verbal consent cue use, and these
associations will not differ by gender.

### Aim 2: Estimate within-person associations between proximal, event-level factors and consent cue usage.

We will examine relational, perceptual, and behavioral time-varying
correlates of consent cue usage. **Hypotheses:** *(H2a)* Greater
differences in participant vs. perceived partner intoxication will be
positively related to consent cue use for encounters involving more
familiar partners (current/former dating partner \> friend \>
stranger).  *(H2b)* Lower levels of physical intimacy (kissing,
touching) and greater participant alcohol consumption will be negatively
related to consent cue use when controlling for whether partners have
shared sexual history.

### Aim 3: Examine the added value of situational correlates beyond person-level predictors for explaining variance in consent-cue use and evaluate whether cross-level interactions improve model fit.

Considering the relative nascency of this literature, we will use
findings from Aims 1 and 2 to determine whether there are interactions
that should be considered in addition to the following
theoretically-driven interaction tests.  **Hypotheses:** *(H3a)* The
negative association between permissive individual attitudes toward
alcohol-involved consent and cue use will be stronger for encounters
involving participant alcohol consumption. *(H3b)* On days when
participants drink more than their own average, consent cue use will be
significantly reduced after accounting for the effects of aggregate
alcohol use across the study period.

## BACKGROUND AND SIGNIFICANCE

### Importance of understanding between-person predictors of active consent cues.

Rates of sexual assault on U.S. college campuses remain virtually
unchanged after more than 30 years of dedicated research and
intervention.17,18 Lack of consent is increasingly recognized as
defining characteristic of sexual assault, leading institutions to
incorporate consent-focused education into violence prevention
efforts.19,20 University policy and educational initiatives promote
explicit and enthusiastic consent communication (“only yes means yes!”),
while young people often rely instead on passive cues (not resisting,
not saying no) and assumptions (“We love each other”)9 to determine
consent.5,21 Sexual consent education aims to promote the use of active
cues by enhancing consent knowledge and positive attitudes while
decreasing rape-supportive attitudes, presuming that attitudes shape
consent behavior. However, these interventions do not have a clear
underlying mechanism of behavior change, and they rarely assess
behavioral outcomes.19,23 A prerequisite to improving upon the value of
consent education is testing whether these attitudinal intervention
targets predict actual in-the-moment cue use and contrasting their
explanatory power with that of other between-subjects factors.

### Attitudes and adherence to social norms

#### Individual differences

Rape-supportive attitudes and beliefs have been theorized to explain
variability in how individuals approach consent communication.43 Perhaps
the most prominent example in the sexual assault and consent literatures
concerns Rape Myth Acceptance (RMA), the endorsement of widely-held
false beliefs that justify sexual aggression and place blame on
victims.44,45 RMA is a robust predictor of sexual violence perpetration;
it also has been used as an outcome measure in several sexual consent
interventions delivered to young people in educational settings.23,46
Individuals with high levels of RMA often hold the belief that victims
of sexual assault “led the other person on” (e.g., with what could be
conceived through this lens as nonverbal consent cues) or provided
verbal agreement and “later regretted it.” These pervasive schemas
suggest individuals with high levels of RMA may pursue sexual contact
without first communicating their willingness or looking for indications
of the other person’s openness to their advances.47,48 There also are
rape myths that specifically excuse perpetrator behavior in the context
of alcohol intoxication (e.g., “It shouldn't be considered rape if the
person is drunk and didn't know what they were doing”). Rape myths are
distinct from but related to permissive Alcohol and Sexual Consent (ASC)
attitudes,48 both of which contradict sexual assault programming
messages about, for example, how communication signals are easily
misinterpreted when alcohol is involved in a sexual situation.
Permissive ASC attitudes reflect social norms that are prevalent on
college campuses (e.g., “Consensual drunk sex is a normal and harmless
part of college life”) and reinforce approval of intoxicated sexual
activity without regard for the associated risks. Our previous research
found that permissive ASC attitudes were negatively related to ongoing
and communicative (i.e., “process-based”) consent behavior among college
men.4,49 *Highlight interaction with perceived peer attitudes to
facilitate transition*

#### Perceived-peer differences

Among college men, peer relationships can be critical to their risk of
perpetrating sexual aggression37,38 and male peer support for abuse and
coercion have been linked to lower comprehension of sexual consent and
less communicative sexuality.4,39 The relevance of a person’s beliefs
about their peers’ ideas of what is normal and acceptable is best
contextualized by the “sociality of consent,” which refers to a
phenomenon wherein sexual consent is not determined privately between
partners but rather extended into the peer group.40 Qualitative research
assessing how young adults use relational and social contexts to
determine consent further underscores the salience of peer influence, as
participants–particularly college women–described their friends asking
them to help interpret and even make judgments about consent on their
behalf after consuming alcohol or other drugs.31,40–42

### Typical and historical behavior

#### Hazardous alcohol use and sexual risk-taking

Alcohol is a salient factor in the context of both sexual assault and
consensual sex among college students, yet sexual assault prevention and
risk-reduction programs rarely include information about how alcohol can
affect consent communication.21 While scholars and practitioners have
started integrating alcohol and sexual assault programming,27,28 there
is far more research on alcohol-related sexual assault compared to
consent involving alcohol use.22 Some research suggests that young
adults who engage in binge drinking generally use less active consent
communication than those who do not binge drink,5 but the intensity of
alcohol consumption at the encounter level may be more directly relevant
to in-the-moment. Still, cross-sectional surveys cannot establish
whether real-world drinking events decrease the incidence of active
consent cues, and few micro-longitudinal studies have explicitly
investigated situational factors linked to within-person differences in
consent communication.

### Situational correlates of within-person variability in consent cue usage

#### Event-level alcohol consumption

As previously mentioned, Willis and colleagues found no significant
event-level associations between alcohol use and consent cues.10 A daily
diary dissertation study found that, among college women engaging in
casual sex, Blood Alcohol Estimate was negatively associated with
consent expression, but this relationship was no longer significant when
the sexual behavior type was included in the model.11 One potential
explanation is that an individual’s alcohol consumption is more likely
to result in them communicating consent differently than they typically
would on days when their alcohol use is also atypical–representing a
deviation from their own personal norm. This hypothesis is supported by
previous research which shows that, on days when women drink more than
their own average, they are more likely to experience negative sexual
consequences later that day.29,30

#### Event-level perceived intoxication

Young adults also recognize and describe themselves adjusting the
strategies they use to communicate sexual consent based on their
perceptions of their own intoxication relative to that of a potential
partner, but this recurring theme in qualitative and vignette-based
research has proven difficult to explicate quantitatively.31,32 One
hypothesis is that the extent to which perceived differences between
one’s own and their partner's intoxication relate to their use of verbal
consent cues depends on their level of familiarity with that partner.
For example, if someone knows the other person involved in a sexual
encounter well and is motivated to maintain a positive relationship with
them moving forward, they may be more motivated to voice their own
consent verbally and to check in with that other person about their
degree of intoxication and capacity to consent before proceeding with
sexual activity. This hypothesis is supported by the ‘date rape’
literature, which indicates that sexual assaults involving mutual
alcohol consumption are more likely to take place outside the home and
involve someone less well known to the victim.33

#### Relationship to partner and sexual precedence

The relationship or degree of familiarity between two people involved in
a sexual encounter has been related to differences in consent
communication, though existing research has produced paradoxical
conclusions regarding the nature of these associations. Sexual
precedence–the idea that engaging in consensual sex at one point in time
implies consent can be assumed for future encounters with that same
person–is supported by research showing people perceive a greater need
to directly communicate about consent when partners are not in a
committed relationship.24 Yet, cross-sectional survey research among
U.S. college students indicates that explicit verbal consent cues are
less likely to be used when the sexual relationship is casual.7 Internal
consent feelings (safety, comfort) tend to be higher for encounters with
committed dating partners and lower for one-time partners,25 and
internal consent feelings are strong predictors of consent cue use, but
patterns observed over time within relationships suggest a complex
relationship between shared sexual history and consent communication
that warrants further evaluation.26 …This disconnect is one of many
highlighting the need for research grounded in university students’
real-time lived experiences that can help to explain what relational and
situational contexts are related to differences in how they use cues to
communicate sexual consent.

### Significance of method and defense of measures

Experiential sampling via daily reports can facilitate a more nuanced
understanding of the contexts that make verbal and nonverbal consent
communication less likely during college students’ sexual encounters.
Knowledge of these contextual factors can then be used to inform
ecological momentary interventions designed to be delivered when and
where the evidence suggests they will be most effective–an approach that
has shown promise for reducing risk of sexual revictimization among
college women.22

Despite the need for and potential benefits of conducting sexual consent
research using experience sampling methods (ESM), there also are
drawbacks associated with this approach. One such challenge is the
increased burden that repeatedly completing assessments places on
participants. Researchers conducting ESM studies can mitigate
participant burden by making surveys brief, a common but imperfect
solution that frequently necessitates measuring variables with just a
few items per construct (Van Hooff et al., 2007). Measures composed of
only one or two items are often criticized by researchers with
well-founded concerns that they might be more susceptible to measurement
error or fail to capture complex constructs (Fisher & To, 2021). Others
claim that repeatedly administering assessments yields multiple
indicators that decrease random measurement error (Csikszentmihalyi &
Larson, 2014; Shiffman et al., 2008), and that relying on single-item
measures is acceptable when these items are carefully developed and
evaluated for multiple sources of measurement validity.

In the sections that follow, I present cumulative evidence that the
items used to capture the outcome variables in the current research do
indeed measure what they were intended to measure. Specifically, college
students' self-assessments of the degree to which they used verbal and
nonverbal cues to communicate about consent during a partnered sexual
encounter occurring within the past day.

#### Development of consent cue measures

Active consent communication is the use of words or behaviors (i.e.,
cues) to communicate to another person agreement to engage in sexual
activity. It is also referred to as "external" consent communication
because these words and behaviors are used to outwardly express one's
*internal feelings* of willingness to participate in the sexual
behavior. Although prior research reviewed in this proposal suggests
that sexual consent varies from one encounter to the next, the only
validated consent measures that existed until recently were those
developed for cross-sectional research. As such, Willis and colleagues
(2021) used a two-phase procedure to develop and evaluate brief measures
of internal consent feelings and external consent cues specifically
designed for use in ESM studies.

In Phase I, the research team sought to develop items that best
represented the constructs of interest while demonstrating both face
validity and content validity. To do so, operational definitions for the
constructs of interest were derived from seminal theoretical research
and systematic reviews of the sexual consent literature. Cognitive
interviews were then conducted with sexually active adults (*n* = 10)
using concurrent probing to assess sample item comprehension, preferred
wording, and interpretation. Three content-matter experts from the field
of sexual consent research and three measurement experts with doctoral
training in psychometrics also provided ratings to determine the degree
to which sample items captured their corresponding operational
definitions. The research team then calculated IIOC values for content
alignment (cutoff .75) to establish which prospective items had higher
content validity. Items were selected for Phase II by by balancing
participants' judgments and experts IIIOC ratings.

In Phase II, items derived and refined in Phase I were administered in a
seven-day pilot study, with the ESM survey sent to participants (*n* =
12) four times per day. Following the study period, pilot participants
completed an exit survey that collected feedback on the sexual consent
measures and assessed their acceptability in the broader context of the
ESM study. Findings included event-level associations with convergent
and discriminant patterns consistent with theory and previous research.
For instance, verbal and nonverbal consent cues were positively
associated with internal consent feelings of safety/comfort and
readiness; verbal cue use was also positively associated with internal
feelings of agreement/want, while nonverbal cue use was not. Further,
replicating prior work, external consent communication was not
associated with alcohol use at the encounter level for participants in
committed relationships (Jozkowski & Wiersma, 2015). We contextualize
these results and the pilot participants' feedback in the sections that
follow, which concern gaps in validity evidence addressed in subsequent
research, as well as the use of these external consent measures and
their psychometric properties in the current sample.

#### Validity indicators in subsequent research

Willis and colleagues (2021) established feasibility for ESM
administration and solid content and response-process foundations for
their external consent cue items. However, gaps remained in the evidence
base for these measures' validity following their initial publication,
some of which have since been addressed in subsequent research. For
example, the concurrent, within-person associations between internal and
external consent were consistent with preexisting theory and research
that asserts these are separable but related facets of a
multidimensional sexual consent process. Still, the pilot study used
simple event-level correlations and did not offer support for
between-person convergent or concurrent validity. Subsequent research
provides further evidence that the consent cue items' are valid.

Recent recommendations for validating single-item measures for
experience sampling studies call for concurrent within-person
associations, as well as situational sensitivity that demonstrates
predictable within-person changes linked to theory-driven contextual
correlates (Wolfers & Baumgartner, 2025). Guidelines from the field of
communication science suggest evidence concerning concurrent validity at
the within-person level is present when a distinct but
theoretically-related variable significantly predicts the focal outcome
with a standardized effect size greater than .09 (Wolfers & Baumgartner,
2025). This was the case in subsequent research by Willis and
colleagues, who fit multilevel models and found that a composite
internal consent feelings score significantly predicted verbal (β = .53,
p \< .001) and nonverbal (β = .45, p \< .001) consent cue use (Willis,
Jozkowski, et al. 2021, AssessingWithinPerson). The same study
demonstrated event-level situational sensitivity to type of sexual
behavior within the same person with the finding that encounters
involving more intimate sexual behaviors predicted higher consent
communication scores compared to encounters reported by the same person
involving less intimate sexual behaviors (β = .32, p \< .001).

To establish multi-level validity of single-item ESM measures, evidence
is required both within and between-persons. Recent research by Shi and
colleagues (2025) offers support for between-person concurrent validity
in a sample of Chinese adults in mixed-gender relationships.
Specifically, explicit-verbal consent communication significantly
predicted greater sexual satisfaction during participants' most recent
sexual experience with their partner (β = .31, SE = .01, R2 = .10, p \<
.001), and implict-verbal consent significantly predicted greater
general sexual satisfaction (β = .13, SE = .01, R2 = .08, p \< .001).

#### Measurement validity in the current study

#### Outcome Measures

Verbal and nonverbal consent cue use was measured with items developed
for use in studies employing experience sampling methods,60 which
require more brief assessments due to the increased burden on
participants. These measures were based on items previously validated
for use in cross-sectional survey.25,61  After reading the question
stem, “To what extent did you do the following during sexual activity?”
participants rated the following three items on a unipolar, 11-point
sliding scale ranging from 0 (“Not at all”) to 10 (“Very much”).

\
**Verbal:** “Directly asked your partner or communicated verbally with
your partner about consent.”

{{< embed notebooks/fig1.qmd#fig-1 >}}

**Direct, nonverbal:** “Used direct nonverbal signals to communicate
with your partner about consent for the sexual activity.”

**Indirect, nonverbal:** “Used subtle signals to communicate with your
partner about consent for the sexual activity.” The ‘direct’ and
‘indirect’ nonverbal items were highly correlated and thus averaged to
create a composite nonverbal score. Consistent with prior research
finding internal reliability was not strong for a composite including
Verbal, Nonverbal, Direct, and Indirect consent cues,12 Verbal and
Nonverbal cue use were only weakly correlated (r = .13) in the current
sample, so this study will use a composite ‘Nonverbal’ item and examine
Verbal cue use separately.

![Mobile view of consent cue items in daily
survey.](images/cues_mobile.png){width="315"}

## Method

The proposed research will use baseline and 28-day daily diary data to
move beyond the limitations of prior studies, allowing us to consider
interdisciplinary correlates of active verbal and nonverbal sexual
consent behavior across levels of analysis. Any distal, person-level
predictors identified as important will have their relative
contributions verified in a model that also includes proximal
situational factors, increasing confidence that these are reliable
targets for intervention or further theory development. Our lab
collected these data from students at a large public university in the
midwestern U.S. between October and mid-December of 2022.

### Procedures

The research team used Qualtrics to construct a series of data
collection instruments for web-administration, and SurveySignal to send
daily text messages with links to each daily diary survey. After
providing informed consent, participants gained access to the baseline
assessment via Qualtrics. After completing the baseline, each
participant received (1.0) class credit as compensation, which
translates to an additional percentage point on their final grade in
their introductory psychology course. Students with a smartphone were
then given the option to participate in the daily diary portion of the
study. Every day for 28 days, each participant who opted in received a
text message between 11:00 AM and 2:00 PM with a link to that day’s
survey. Each day, those who had not yet opened the survey link also
received a reminder text message two hours after the initial text was
sent. For each complete daily diary, participants received 0.25 class
credits as compensation. To incentivize responding, participants who
completed all 28 daily diary surveys received a \$20 Amazon.com gift
card in addition to the 7.0 extra credit percentage points (28 x 0.25
class credits).

### Participants

We used Sona Systems to recruit participants from an online subject pool
of undergraduates taking introductory psychology courses. We invited
eligible students to participate via email. Participants were made aware
that the study had two parts: a 30-minute baseline survey, and up to 28
daily diary surveys. At the end of the baseline survey, students were
asked whether they had a smartphone AND whether they wanted to opt into
the daily diary portion of the study. Those who responded affirmatively
to both were enrolled in Survey Signal and pushed daily survey links
through SMS for up to 28 days. 

Eligible participants were those 18 years or older who owned a
smartphone and reported consuming at least one alcoholic beverage in the
past year. A total of 386 students met eligibility criteria and
completed at least 20% of the baseline assessment. Of these, 278
students participated in the daily diary portion of the study.
Participant ages ranged from 18 - 23.

Participants who endorsed partnered sexual activity (n = 152) reported
501 events in total...

## Measures

The baseline and daily diary surveys were designed to capture
theoretically and empirically supported personal and contextual factors,
respectively. The measures we selected were drawn from peer-reviewed
research examining sexual consent and sexual assault. Importantly, the
diaries asked about experiences and behaviors since the last survey, so
event-level factors are anchored to the context of the same sexual
encounter. 

### Baseline

Demographic measures assessed gender, age, race, sexual orientation,
year in school, relationship status, campus involvement (e.g., Greek
life, athletics), residence (e.g., dormitories), disability status, and
socioeconomic status. Individual attitudes: assessed with the Illinois
Rape Myths Acceptance scale (7 items);48 Sociosexual Orientation
Inventory (3 items);50 and the subtle coercion subscale of the
Process-Based Consent scale.51 Perceived peer attitudes: assessed with
the Rape Attitudes and Beliefs Scale (2 items)52 and Alcohol and Sexual
Consent scale (2 items).49 Individual behavior: assessed with the
Alcohol Use Disorders Identification Test (10 items);53 original and
adapted Sexual Risk Behavior Scale (6 items);54,55 and Sexual Consent
Scale-Revised (3 items).56 Trait emotion dysregulation was assessed with
the Difficulties in Emotion Regulation Scale (16 items).57

### Daily Dairy

Each diary prompted participants to report on behaviors and experiences
since their last survey and began with five daily behavioral screening
items assessing (1) partnered sexual behavior, (2) alcohol use behavior,
(3) online sexual behavior, (4) solitary sexual behavior, and (5) drug
use behavior. We designed the daily surveys so that each participant
would complete 1-2 survey blocks per day assigned based on their
responses to the behavior screening items. When a participant responded
“No” or “Prefer not to respond” to all five screening items with
corresponding behavior blocks, they were assigned to a general mental
health block. Survey blocks were all comparable in length and focused on
sensitive topics to discourage selective responding and ensure that each
person received roughly the same number of follow-up questions per day,
regardless of the experiences they endorsed on the screening items.
Survey blocks were rank-ordered from 1-5 and prioritized partnered
sexual behavior and alcohol use behavior data, such that, whenever a
participant responded “Yes” to more than two behavioral screening items,
branching logic directed them to the two-highest ranked survey blocks.

#### Partnered sexual behavior

In each of the daily surveys, participants responded to the following
screening item, “Since the last survey, have you hooked up, engaged in
any sexual activity, or tried to engage in any sexual activity with
another person (including flirting, kissing, touching, or intercourse)?”
Response options included: Yes (= 1), No (= 0), Prefer not to respond (=
3). 

#### Relational

**Relationship to partner:** Participants responded to the question,
"How did you know this other person?" by selecting one of the following
familiarity levels from a list of response options: “I didn’t, we just
met that day;” “They are an acquaintance;” “They are a friend;” and
“They are my current or past dating/intimate partner.”

**Sexual precedence:** Participants responded to the question, “Had you
ever had sexual contact with this person in the past?” with response
options Yes (=1) and No (=0). 

#### Perceptual

**Perceived intoxication:** Participants rated their own intoxication
("How intoxicated did you feel right before or during this sexual
activity?") and their perception of their partner’s intoxication ("How
intoxicated do you think the other person felt right before or during
this sexual activity?") using a sliding scale from “Least intoxicated
ever felt” (=0) to “Most most intoxicated ever felt” (=100). 

**Intoxication disparity:** A continuous "intoxication disparity"
variable will be calculated as the absolute difference between
self-reported intoxication and perceived partner intoxication. Larger
values indicate lower perceived alignment between self- and partner-
intoxication. We also will create a factor variable with categories for
equal intoxication (Parity), for when the participant perceived
themselves as more intoxicated (Self-Higher), and for when the
participant perceived the partner as more intoxicated (Partner-Higher).

#### Behavioral

**Sexual behavior type:** Participants were instructed to select all
that apply from a list of specific behaviors we will use to create an
ordinal event-level variable that captures escalating levels of physical
intimacy aligned with previously established sexual hierarchies: Kissing
(=1); Touching (=2); Penetration with fingers or fingering (=3); Oral
sex (=4); Vaginal sex (=5); and Anal sex (=6).**58** An additional
response option read, “I tried but no sexual contact happened,” and
encounters for which this was the only response will not be included in
the present analysis.

**Pre-encounter alcohol consumption:** Participants were asked, “How
many drinks did you consume prior to or during this activity?” with
response options for the following drink counts: 0; 1-2; 3-4; 5-6; 7-9;
and 10+ drinks.

#### For assessing outcome measure validity

**Arousal and pleasure:** Participants’ subjective sexual feelings of
arousal and pleasure were measured with single self-report items that
followed from the question stem, “To what extent did you feel the
following during the sexual activity?” Participants were instructed to
rate the statements, “I felt aroused” and “I felt pleasure” using a
unipolar, 11-point visual analogue (sliding) scale ranging from 0 (“Not
at all”) to 10 (“Very much”).60 

### Analytic Strategy

Analyses will include all encounters that involved sexual contact. Study
objectives include: (1) characterizing between-person variation in
consent cue use, (2) identifying proximal contextual correlates by
estimating within-person associations between event-level factors and
consent cue use, (3) determining whether, and to what degree, contextual
factors provide added explanatory power beyond person-level factors (and
vice versa) for describing differences in consent cue use. For aims 2
and 3, we are characterizing associations for concurrent, within-window
data; I do not make any claims about causal prediction.

#### Pre-processing

Prior to model fitting, I will compute scale scores and mean-center
continuous variables to facilitate interpretation of coefficients and
interactions. I will dummy-code categorical variables for comparability.
I will diagnose and report multicollinearity among conceptually
overlapping variables, inspecting and reporting bivariate correlations
and Variance Inflation Factors (VIFs). I will describe missingness
patterns for all variables and treat \>5% missing data on a given
variable as non-trivial, applying multiple imputation in those cases.

#### Aim 1: Between-person predictors of consent cue use

To address Aim 1, we will test hypotheses concerning person-level
predictors (L2) by estimating multivariate linear mixed-effects models
(LMMs) with Gaussian residuals to jointly model verbal and nonverbal
consent cue outcomes. Modeling both outcomes simultaneously allows us to
account for their correlation at the residual level, formally test
whether predictors operate differently across outcomes, and increase
efficiency in estimating shared effects. A random intercept will be
specified to account for repeated sexual events nested within
participants. Models will be estimated using maximum likelihood (ML) for
hypothesis testing and restricted maximum likelihood (REML) for final
effect size estimation. Standardized fixed-effects coefficients with 95%
confidence intervals and marginal-effects plots will be reported to
convey effect size and direction.

#### Aim 2: Within-person correlates of consent cue use

The second aim focuses on event-level variability, consistent with
recent evidence showing that between 50% and 80% of the variance in
sexual consent cues can be attributed to within-person fluctuations
across sexual events.12 To isolate within-person processes, I will fit
multivariate Gaussian LMMs that jointly model verbal and nonverbal
consent cues, include participant random intercepts, and, when
supported, random slopes for situational predictors. Event-level
predictors will be person-mean centered to disaggregate within-person
effects from between-person effects. Models will estimate residual
covariance between outcomes; estimation will use ML for nested model
comparisons and REML for final reporting. Primary parameters are
within-person slopes linking situational factors to each outcome. We
will examine residual diagnostics and heteroscedasticity.

#### Aim 3: Incremental value and testing interactions

Building on Aims 1 and 2, significant person-level (L2) predictors will
be entered into a multivariate LMM with significant event-level (L1)
correlates to evaluate the value of these time-varying situational
factors above and beyond individual factors for explaining variability
in consent cue use. For model comparisons and cross-level interaction
tests, improvements in fit will be evaluated using likelihood ratio
tests (LRT); changes in ΔAIC/ΔBIC and Δmarginal/conditional R2 will be
reported. We will visualize conditional marginal effects (simple slopes)
of predictors across meaningful moderator values (e.g., gender; ±1 SD
emotion dysregulation;  ±1 SD permissive attitudes toward
alcohol-involved consent), with 95% CIs.

#### Preliminary Analysis

I will use quarto inline to display math equations. Quarto provides
[details](https://quarto.org/docs/authoring/markdown-basics.html#equations)
on the use of these equations.

For example $x$ and $y$ are two variables. And here is an important
formula:

$$
p(x) = \frac{e^{-\lambda} \lambda^{x}}{x !}
$$

To add results that are not figures or tables, I will open the objects I
saved from these analyses. See lm.qmd as an example. Generally, I will
open csv files that contain tidied results. For example:

```{r,echo=FALSE,message=FALSE,warning=FALSE}
library(tidyverse)

coeffs <- read_csv(here::here("objects/coeff_table.csv"),
                   col_types = cols())
```

A significant effect was observed ($\beta$ =
`r sprintf("%1.1f", coeffs |> filter(term == "aud_sc") |> pull(estimate))`,
t =
`r sprintf("%1.2f", coeffs |> filter(term == "aud_sc") |> pull(statistic))`,
p =
`r sprintf("%1.3f", coeffs |> filter(term == "aud_sc") |> pull(p.value))`).

#### Potential Problems and Alternative Strategies

Considering the multiple subscales and items per domain in Aim 1, if
diagnostics reveal predictors are highly correlated, we will prioritize
individual attitudes over perceived peer attitudes and drop the latter
when indicated by \|r\| ≥ .7 - .8. If Variance Inflation Factors (VIFs)
\> 5, we will estimate a multilevel confirmatory factor analysis (CFA)
for the individual attitudinal items and regress consent cue outcomes on
the latent factor(s) to handle collinearity.

To address potential ceiling effects on the 0-10 outcome scales, we will
conduct a sensitivity analysis by fitting univariate cumulative link
mixed models (CLMMs) with the same fixed-effects structures and consider
conclusions robust when signs and inferences align. If models do not
converge in a maximum likelihood framework, they will be estimated in a
Bayesian framework (e.g., using the brms package in R). 

#### Limitations and Future Directions

The proposed research is not without limitations. First, there were
measures not included in this data collection effort that we intend to
prioritize in the future. Considering this project focuses on active
consent communication, we did not measure passive “no response” signals,
which are commonly reported cues used to infer and communicate consent
among young adults despite risks associated with their ambiguity and
inconsistent associations with internal willingness.2 Also, we did not
assess refusal cues that participants may have used to indicate lack of
willingness, so it is possible that participants were also reflecting on
behaviors they used to assert boundaries when responding to items
assessing verbal and nonverbal consent cues. Other measures not included
that could have strengthened the current study are perceptions of
partner cue usage, because we cannot speak to how participants inferred
consent from their partners without those data, nor can we know whether
the body language, behaviors, or comments that participants interpreted
as cues were intended to signal consent. In future research, these
limitations can be addressed through dyadic data collection, though
recruiting in pairs introduces a different set of constraints with
respect to feasibility and generalizability. Finally, we did not provide
options to select from or ask participants to report specific examples
of the behaviors that they were classifying as verbal or nonverbal cues,
and we did not provide participants with the operational definitions for
these constructs prior to study initiation. 

Specific characteristics of the current study sample and design also may
limit what can be accomplished with the proposed research. Participants
were recruited via Sona Systems and compensated with extra credit in
their introductory psychology class, resulting in a college-student
sample with 85% of participants in their first year. More than 90% of
the sample fell below age 20, while a sample with more proportional
representation of upperclassmen may have yielded a greater number of
partnered sexual events and drinking episodes for analysis. Further, as
these data were collected from college students at a primarily white
institution in the midwestern U.S., the sample is homogeneous in terms
of race (77% White) and sexual orientation (87% heterosexual).
Directions for future research include more stringent criteria that
require eligible study participants be sexually active; prior sexual
experience was not an inclusion criterion for participating in the
current research, as it is common for young adults’ first partnered
sexual experiences to occur during their first semester at
university.62 

With respect to study design, the experience sampling method used to
support this project was a relative strength compared to the primarily
cross-sectional literature in this area. Using electronic diaries
reduced the timeframe for retrospective recall, however, survey timing
and framing still required participants to think backwards when
reporting on behaviors and experiences that preceded sexual events
(e.g., pre-encounter affect, drink estimates) on the previous day. Thus,
results examining event-level variables can only be interpreted as
associational and predictive within the concurrent window. Additionally,
asking participants to rate, for example, a sexual partner’s
intoxication level relative to their own at the same timepoint that we
asked them about sexual consent communication may have increased
susceptibility to social desirability bias, potentially leading
participants to respond in ways they thought would be perceived more
positively by the research team, or in ways that reduced their own
cognitive dissonance around possibly taking advantage of an intoxicated
person or being taken advantage of themselves. In future research, these
limitations could be addressed using ecological momentary assessment
with ≥2 surveys per day and/or event-contingent sampling, permitting
assessment of contextual variables pre-encounter and
concurrent/post-encounter variables immediately thereafter. Finally,
there is risk of overfitting to sample-specific nuance, as we are
fitting and evaluating our models in the same sample; techniques for
estimating out-of-sample generalizability were considered but ultimately
omitted from the analytic plan, which prioritizes feasibility.
Directions for future research include goals to replicate our findings
in a separate college sample of new participants, as well as among young
adults in other sociocultural contexts.

## References

::: {#refs}
:::
